### ISSUE TITLE
TooManyRequestsException while running components

### ISSUE THREAD

**Issue by volkancoskun** [serverless-components/aws-api-gateway#8]
Hey all, 

I changed YML file according to new structure, but now im getting `TooManyRequestsException.`

Stacktrace:
```

  { TooManyRequestsException: Too Many Requests
    at Object.extractError (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/volkan.coskun/.serverless/components/registry/npm/@serverless/aws-api-gateway@0.1.8/node_modules/@serverless/aws-api-gateway/node_modules/aws-sdk/lib/state_machine.js:26:10
  message: 'Too Many Requests',
  code: 'TooManyRequestsException',
  time: 2019-05-24T09:36:49.783Z,
  requestId: '748deda3-7e07-11e9-a3c3-6bc5c5fb295f',
  statusCode: 429,
  retryable: true }
```

Its time critical issue for me, 
thanks for help.

**Comment by eahefnawy** [comment]
thanks @volkancoskun ... could you share your yaml file?

**Comment by volkancoskun** [comment]
hey @eahefnawy i downgraded the api-gateway version to **@serverless/aws-api-gateway@0.1.6.** Its working fine now. Because of that i changed yaml structure as old one. I ll try newer version again. After that i can share my yaml file.

**Comment by eahefnawy** [comment]
@volkancoskun ok how many endpoints do you have exactly?

**Comment by volkancoskun** [comment]
@eahefnawy 53 endpoints.

**Comment by eahefnawy** [comment]
wow! what's your application about? 🤔

**Comment by Pavel910** [comment]
@eahefnawy I ran into this issue today. I am deploying 4 API Gateways, each has 1-3 endpoints, but my problem is not the amount of endpoints but the call to [createDeployment](https://github.com/serverless-components/aws-api-gateway/blob/master/serverless.js#L110).

I think the AWS SDK is complaining because I'm creating 4 deployments (each for a different gateway) in a short period of a few seconds. I have a working solution, which looks like this:

```js
await pRetry(() => createDeployment({ apig, apiId, stage }), {
  retries: 5,
  minTimeout: 1000,
  factor: 2,
  onFailedAttempt: error => {
    this.context.debug(
        `[WARNING] Attempt ${error.attemptNumber} failed. There are ${error.retriesLeft} retries left.`
    );
  }
})
```

So the idea is to use the [p-retry](https://www.npmjs.com/package/p-retry) library to retry failed requests with an increasing back-off time each time it fails. I know you want to keep the dependencies at a minimum, so I checked the `p-retry` size, and it's [very small](https://bundlephobia.com/result?p=p-retry@4.1.0).

The resulting output looks like this:
```
 DEBUG ─ Creating deployment for API ID y8opwtkccl in the prod stage and the us-east-1 region.
 DEBUG ─ Creating deployment for API ID ygx6sbx1j1 in the prod stage and the us-east-1 region.
 DEBUG ─ Removing any old endpoints for API ID rw5fktns60.
 DEBUG ─ Creating deployment for API ID rw5fktns60 in the prod stage and the us-east-1 region.
 DEBUG ─ Deployment successful for the API named jiqanxu-3wcke3t in the us-east-1 region.
 DEBUG ─ API URL is https://y8opwtkccl.execute-api.us-east-1.amazonaws.com/prod.
 DEBUG ─ Deployment successful for the API named jiqanxu-4od066p in the us-east-1 region.
 DEBUG ─ API URL is https://ygx6sbx1j1.execute-api.us-east-1.amazonaws.com/prod.
 DEBUG ─ [WARNING] Attempt 1 failed. There are 5 retries left.
 DEBUG ─ [WARNING] Attempt 2 failed. There are 4 retries left.
 DEBUG ─ [WARNING] Attempt 3 failed. There are 3 retries left.
 DEBUG ─ Deployment successful for the API named jiqanxu-iek2zwr in the us-east-1 region.
 DEBUG ─ API URL is https://rw5fktns60.execute-api.us-east-1.amazonaws.com/prod.
```

### Why so many API Gateways?
Our platform uses Apollo Federation to build GraphQL APIs using the microservices approach, so each API Gateway instance is a separate microservice, and the last instance is the one that glues everything together - and it contains the URLs of all the child services. With this fix I no longer have failing deploys.

Since AWS is so sensitive in regards to amount of sequential API calls, I think this fix will be useful.
I can send a PR if you agree to implement it.

Let me know if you need more info/details. I'll be happy to discuss further :)

**Comment by eahefnawy** [comment]
@Pavel910 absolutely! This is likely how I would've solved it as well. PR most welcome 😊

**Comment by eahefnawy** [comment]
@volkancoskun could you try out #13  and let us know if this is sufficient for your issue? 😊
